### PR TITLE
Add dependencies check and installation

### PR DESCRIPTION
**Pull request by 29988122**
I assume that this is more friendly for testing purposes, as people sometimes don't read manual files?
No idea if it's necessary in your opinion.

P.S. Great repo, easier for me to tinker and experiment with than Aztec's and dusk's implementation, considering the fact that we can use circom to write circuit in plonkit.

### CODE REVIEW

**Comment by HAOYUatHZ** [comment]
Thanks for your contribution!

Are you using MaOS? This improvements seems not working on Ubuntu. 

BTW could you also increase the subsequent "step" number?

**Comment by 29988122** [comment]
I'm using ubuntu 20 LTS. 
https://www.cyberciti.biz/faq/find-out-if-package-is-installed-in-linux/

Is dpkg not existent on your OS? I could try some hacky solution like checking if the npm/axel binary exists or not.

**Comment by HAOYUatHZ** [comment]
I am also using ubuntu 20.04.

But I am getting
```
dpkg-query: no packages found matching axel
```

Any idea?

**Comment by HAOYUatHZ** [comment]
BTW I think people prefer nvm to manage node/npm stuff

**Comment by HAOYUatHZ** [comment]
> I am also using ubuntu 20.04.
> 
> But I am getting
> 
> ```
> dpkg-query: no packages found matching axel
> ```
> 
> Any idea?

A working around is to `sudo apt  install axel` directly.   `apt` itself will check installation for us.

**Comment by 29988122** [comment]
Should be better now, modified the binary path checking, and the installation of nvm if npm binary's not found.
See if there's any bugs!

**Comment by HAOYUatHZ** [comment]
Thanks! @29988122

**Pull request merged**
